### ISSUE TITLE
[style suggestion] vyhnout se skloňování anglických termínů

### ISSUE THREAD

**Issue by marbu** [fbalak/dp#16]
Dopuručuju vyhnout se skloňování přejatých slov, co se ještě v češtině nestihly asimilovat. Např.:

> Definice text miningu

není uplně dobré psát v diplomce. Da se to obejít buď:

* použitím českého termínu (pokud existuje)
* vložením českého slova, které budeš skloňovat místo toho, takže dostaneš ten anglický termín do pvního pádu

**Comment by fbalak** [comment]
Díky, zkusím to zařadit do práce.
